### ISSUE TITLE
QSAR fish toxicity Data Set

### ISSUE THREAD

**Issue by Auguste11** [R-2019-projects/dataset-regstration#14]
**Project ID:** R-2019--proj-09

**Dataset:**QSAR fish toxicity Data Set

1) **Short name:** QSAR fish toxicity Data Set
2) **Full name:** A similarity-based QSAR model for predicting acute toxicity towards the fathead minnow (Pimephales promelas)
3) **Source:** M. Cassotti, D. Ballabio, R. Todeschini, V. Consonni. A similarity-based QSAR model for predicting acute toxicity towards the fathead minnow (Pimephales promelas), SAR and QSAR in Environmental Research (2015), 26, 217-243; doi: 10.1080/1062936X.2015.1018938

**It's my personal data:** no

**Article:**  
a. Article name: A similarity-based QSAR model for predicting acute toxicity towards the fathead minnow (Pimephales promelas), SAR and QSAR
b. DOI: 10.1080/1062936X.2015.1018938
c. URL to article:  https://www.tandfonline.com/doi/abs/10.1080/1062936X.2015.1018938
d. URL to data: https://archive.ics.uci.edu/ml/datasets/QSAR+fish+toxicity?fbclid=IwAR3NQwOpbgB40B_5J9lNnMTf5GlJiK1fV8vwOlAaYqqrKbngnzXFEKFXDyk 

**Repisitory/Data base:**  
a. Repository name:  Center for Machine Learning and Intelligent Systems
b. URL to dataset's webpage: https://archive.ics.uci.edu/ml/index.php
    
**Other relevant information:** ...

**Comment by GegznaV** [comment]
Tas pats projektas #13
